opendistro-for-elasticsearch/performance-analyzer

src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/MasterServiceEventMetrics.java
src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/metrics/MetricsConfiguration.java

Update the writer to sample Master Event Metrics every 1 second.

Set master event metrics sampling time to 1 second

---

src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/jvm/ThreadList.java
src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/metrics/PerformanceAnalyzerMetrics.java

sun.tools.attach.VirtualMachineImpl$SocketInputStream.close not handling double close properly, which will fail in cases like try (BufferedReader br = new BufferedReader( ((HotSpotVirtualMachine) vm).remoteDataDump((Object[]) args));). Fix is: avoiding double close from client side to avoid Bad file descriptor errors

Bad File Descriptor error due to double VirtualMachineImpl$SocketInputStream.close

---

src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/PerformanceAnalyzerPlugin.java

Plugin settings should be initialized only after plugin file location has been setup. Otherwise plugin settings will be initialized with default settings.

Move plugin settings initialization into the plugin constructor

---

pa_config/performance-analyzer.properties
src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/config/PluginSettings.java
src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/metricsdb/MetricsDB.java
src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/reader/ReaderMetricsProcessor.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/reader/ReaderTrimDBTests.java

Currently, the number of most recent metricsdb files to keep around is
determined by a code level constant. In some cases there might be a
requirement to keep more files around (or for the reader to never delete
them). This change introduces a config for that in the
performance-analyzer.properties file named 'max-metrics-db-files'.
Setting this to value -1, makes the files to never be deleted,
otherwise, the acceptable numbers are between 1 and 1000. Anything else
sets the config to default which is 4.
Github issue #47

Making the metricsdb files to keep around configurable.

---

src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/rest/QueryMetricsRequestHandler.java

This commit will add access logs to performance analyzer webservice. 
EG:
[2019-06-05T17:41:42,411][INFO ][c.a.o.e.p.r.QueryMetricsRequestHandler] GET /127.0.0.1:57340 /_opendistro/_performanceanalyzer/metrics?metrics=ShardBulkDocs,ShardEvents&agg=sum,sum&dim=Operation,IndexName&nodes=all

Add access logs to performance analyzer webservice

---

build.gradle
release-notes

1. Add elasticsearch 6.8.1 support
2. Update opendistro version from 0.9.0 to 0.10.0
3. Update release notes

Add elasticsearch 6.8.1 support

---

src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/metrics/PerformanceAnalyzerMetrics.java
src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/metricsdb/MetricsDB.java
src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/rest/QueryMetricsRequestHandler.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/metrics/PerformanceAnalyzerMetricsTests.java

1. Returning status code 400 instead of 500 for the following client side errors -
- When the client does not set the required parameters
- When the client specifies an unknown aggregation type
2. Creating PA events in correct location even if metrics location config value doesn't have a trailing "/"

Bug Fixes -

---

src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/MasterServiceEventMetrics.java
src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/StatsCollector.java
src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/config/PluginSettings.java
src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/metrics/PerformanceAnalyzerMetrics.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/AbstractTests.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/CustomMetricsLocationTestBase.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/action/PerformanceAnalyzerActionListenerTests.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/CircuitBreakerCollectorTests.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/MasterServiceMetricsTests.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/NodeStatsMetricsCollectorTests.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/ThreadPoolMetricsCollectorTests.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/listener/SearchListenerTests.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/metrics/PerformanceAnalyzerMetricsTests.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/reader/MetricPropertiesTests.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/transport/PerformanceAnalyzerTransportChannelTests.java

1. Fix NullPointerException caused due to race between performance analyzer collecting master node metrics and master node completing initialization.
1. Fix unit tests not running on mac due to the unavailability of /dev/shm by setting metrics location explicitly in the tests' initialization.

MasterMetricsError and Mac unit tests fix

---

src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/MasterServiceEventMetrics.java
src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/StatsCollector.java
src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/config/PluginSettings.java
src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/metrics/PerformanceAnalyzerMetrics.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/CustomMetricsLocationTestBase.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/action/PerformanceAnalyzerActionListenerTests.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/CircuitBreakerCollectorTests.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/MasterServiceMetricsTests.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/NodeStatsMetricsCollectorTests.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/ThreadPoolMetricsCollectorTests.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/listener/SearchListenerTests.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/metrics/PerformanceAnalyzerMetricsTests.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/reader/MetricPropertiesTests.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/transport/PerformanceAnalyzerTransportChannelTests.java

Merging the following changes from OpenDistro-1.1
* Fix running unit tests on a mac
* Fix NullPointerException while collecting master event metrics before master node is fully initialized.

Merge fixes from OD-1.1 branch

---

build.gradle
src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/PerformanceAnalyzerPlugin.java
src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/NodeStatsMetricsCollector.java
src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/ValueCalculator.java
src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/config/PerformanceAnalyzerController.java
src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/config/setting/PerformanceAnalyzerClusterSettings.java
src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/config/setting/handler/NodeStatsSettingHandler.java
src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/http_action/config/PerformanceAnalyzerClusterConfigAction.java
src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/http_action/config/PerformanceAnalyzerConfigAction.java
src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/http_action/config/PerformanceAnalyzerResourceProvider.java
src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/writer/EventLogQueueProcessor.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/NodeStatsMetricsCollectorTests.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/http_action/config/PerformanceAnalyzerResourceProviderTest.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/reader/AbstractReaderTests.java

Verified that Performance Analyzer is coming up node and responding.
------------------------------------------------------------------------
[root@da675680feb8 tmp]#  curl localhost:9600/_opendistro/_performanceanalyzer/metrics?metrics=CPU_Utilization\&agg=avg | python -m json.tool
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   157  100   157    0     0  10072      0 --:--:-- --:--:-- --:--:-- 10466
{
"cKK5UuffRPie7kOLr7HT9A": {
"data": {
"fields": [
{
"name": "CPU_Utilization",
"type": "DOUBLE"
}
],
"records": [
[
0.0015881554343092808
]
]
},
"timestamp": 1578529525000
}
}

Adding shardsPerCollection REST API to update the shards Per Collection in Node Stats collector

---

src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/NodeDetailsCollector.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/reader/AbstractReaderTests.java

Add isMasterNode to NodeDetailsStatus. This is a fix required to reduce number of calls made to _cat/master api in rca framework

Add isMasterNode to NodeDetailsStatus

---

src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/JsonKeyTests.java

The _cat/master fix might not be backported to all PA versions in brazil so not all domains has the IS_MASTER_NODE field in NodeDetailsStatus. 
Make the unit test backward compatible with the isMasterNode in NodeDetailsStatus

Make the unit test backward compatible with the _cat/master fix

---

src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/http_action/config/PerformanceAnalyzerResourceProvider.java

The use of String.format here appears to be unnecessary. Also, it triggers exceptions if the request uri has percent-encoded characters like '%2C' (comma).

Remove unnecessary string formatting

---

.github/workflows/gradle.yml
build.gradle

This commit makes it so that you can build PA without running
integration tests. This is useful for many reasons, including being able
to build RCA without depending on PA's integration tests and
dramatically reducing build times.
Integration Testing has been added as part of the Github Actions
workflow.

Run integ tests as part of git workflow instead of build

---

.github/workflows/gradle.yml
build.gradle
gradle.properties
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/PerformanceAnalyzerIT.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/util/WaitFor.java

This commit makes IT execution much more robust and only executes ITs if
the user passes the -Dtests.enableIT flag to the Gradle environment.
This commit also ensures that we bind to all interfaces when we spin up
a local Docker cluster for testing.

Fixup ITs and binding issues

---

licenses/performanceanalyzer-rca-1.3.jar.sha1
src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/ThreadPoolMetricsCollector.java

collect queue capacity on writer. This is to read the capacity from resizable queue in ES. PA will not emit QueueCapacity metric if the patch is not found in core ES.  

collect queue capacity on writer

---

src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/http_action/config/PerformanceAnalyzerResourceProvider.java

PA attempts to set the default SSL Socket Factory (which defines rules
for the SSL Sockets it creates) as well as default hostname verification
rules when it is initialized by the Elasticsearch plugin loader.
However, this behavior would result in an AccessControlException when
run alongside the opendistro-security plugin. This commit is a simple
fix which allows these two plugins to work together.

PA will no longer crash when SecurityManager says no

---

src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/ThreadPoolMetricsCollector.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/ThreadPoolMetricsCollectorTests.java

The current rejection count that PA emit is the overall rejection of all time since the cluster starts. We need to calculate rejection increase between each sampling so that we can easily tell whether rejection occurs in each time interval.  

Calculate rejection increase and emit the delta increase of rejection as metric 

---

build.gradle
checkstyle/findbugs-exclude.xml
src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/http_action/whoami/WhoAmIAction.java

Enable spotbugs. Also address the associated spotbug warnings (see below image):
1: The static initializer was moved to after all static final fields were assigned.
2, 3: This warning was disabled like in the rca repo.
4: The associated code throws both RuntimeException's and ReflectiveOperationException's, and both of them should be handled the same way here. So, this warning should not be raised, so it was disabled.

Enable spotbugs, address spotbug warnings

---

build.gradle
packaging/deb/postinst
packaging/opendistro-performance-analyzer.service
packaging/performance-analyzer-agent-cli
packaging/rpm/postinst

*Description of changes:* Include RCA bits in build distribution

Include RCA bits in build distribution

---

packaging/performance-analyzer-agent-cli

*Description of changes:* Agent script now uses a variable path to elasticsearch-cli

Agent script now uses a variable path to elasticsearch-cli

---

pa_config/supervisord.conf

https://github.com/opendistro-for-elasticsearch/opendistro-build/issues/34
https://github.com/opendistro-for-elasticsearch/opendistro-build/pull/320
Move PA files to subdir owned by elasticsearch user
*Tests:*
[image](https://user-images.githubusercontent.com/65193828/87365444-3d975f80-c544-11ea-8ad0-4a2d4d81320a.png)
*Code coverage percentage for this patch:*

 Move PA files to subdir owned by elasticsearch user

---

.github/workflows/gradle.yml
build.gradle
gradle.properties
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/PerformanceAnalyzerIT.java

*Description of changes:* 
* Uses prop=true/false instead of set/null for property flags
* REST port number for ITs is now configurable
* ITs now work if logging is enabled alongside PA and RCA

IT improvements

---

src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/CacheConfigMetricsCollector.java

*Issue #, if available:* https://github.com/opendistro-for-elasticsearch/performance-analyzer-rca/issues/311
*Description of changes:* Updating the Cache Max Size Dimension to use toString

Updating the Cache Max Size Dimension to use toString

---

src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/CacheConfigMetricsCollector.java

*Description of changes:* Fixing checkstyle build failure caused by unused import. 
Build Failure : https://github.com/opendistro-for-elasticsearch/performance-analyzer/runs/920086188
```
> Task :checkstyleMain
[ant:checkstyle] [ERROR] /home/runner/work/performance-analyzer/performance-analyzer/tmp/pa/src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/CacheConfigMetricsCollector.java:25:8: Unused import - com.amazon.opendistro.elasticsearch.performanceanalyzer.metrics.AllMetrics.CacheType. [UnusedImports]
```

Fixing checkstyle build failure

---

src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/PerformanceAnalyzerIT.java

*Issue #, if available:* #156 
*Description of changes:* Add an IT which verifies that the RCA REST endpoint can be queried

Add an IT which verifies that the RCA REST endpoint can be queried

---

src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/PerformanceAnalyzerPlugin.java
src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/NodeDetailsCollector.java
src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/config/setting/handler/ConfigOverridesClusterSettingHandler.java

Fixes #165 
Fixes #164 
The NodeDetailsCollector instantiation in the plugin was overwritten by change #162 
This change instantiates the node details collector correctly.
This change also gets rid of the confusing stacktrace that gets printed during ES startup.

Use the correct ctor for NodeDetailsCollector

---

src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/config/setting/handler/PerformanceAnalyzerClusterSettingHandler.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/config/PerformanceAnalyzerClusterSettingHandlerTest.java

https://github.com/opendistro-for-elasticsearch/performance-analyzer/issues/152
Fix Cluster settings entering an invalid state. 
Cluster setting references to node values when updating. This causes cluster state to move to an invalid state
Output:
Case1:
Enable PA on a node
Enable RCA/Logging on a node
Enable RCA/Logging on the cluster
```
{
"currentPerformanceAnalyzerClusterState": 0,
"shardsPerCollection": 0
}
{
"performanceAnalyzerEnabled": true,
"rcaEnabled": true,
"loggingEnabled": false,
"shardsPerCollection": 0
}
```
Case2:
Enable PA on a node
Enable RCA/Logging on the cluster
```
{
"currentPerformanceAnalyzerClusterState": 2,
"shardsPerCollection": 0
}
{
"performanceAnalyzerEnabled": true,
"rcaEnabled":false,
"loggingEnabled": …
```

Fix invalid cluster state

---

.github/PULL_REQUEST_TEMPLATE.md
release-notes/opendistro-for-elasticsearch.performance-analyzer.release-notes-1.10.0.0.md
release-notes/opendistro-for-elasticsearch.performance-analyzer.release-notes-1.10.0.md

"Add release notes for 1.10 release

Add release notes for 1.10 release

---

build.gradle
gradle.properties
src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/config/setting/handler/PerformanceAnalyzerClusterSettingHandler.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/ITConfig.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/PerformanceAnalyzerIT.java

*Fixes #, if available:*  #175 
- PerformanceAnalyzerIT is now capable of initializing ES test framework
clients via Basic HTTP Authentication

Update PerformanceAnalyzerIT to work with opendistro-security

---

src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/NodeStatsAllShardsMetricsCollector.java
src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/NodeStatsFixedShardsMetricsCollector.java
src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/util/Utils.java

*Fixes #, if available:* #170 
*Description of changes:* We need to emit the cache hit, miss and eviction metrics as delta rather than absolute values. ES reports these metrics from beginning of process/post an invalidateAll() event/ post cache clear.
This change calculated the metrics count delta between each sampling to correctly reflect the increase/decrease in the metric count for the evaluation Interval (5seconds for us)
This is done for FieldData, Shard Request and Node Query Cache.
*Testing:* Absolute Value of Metrics as taken from ES:  {"Cache_Query_Hit":0,"Cache_Query_Miss":0,"Cache_Query_Size":0,"Cache_FieldData_Eviction":0,"Cache_FieldData_Size":0,"Cache_Request_Hit":0,"Cache_Request_Miss":1,"Cache_Request_Eviction":0,"Cache_Request_Size":757} …

Update the Cache Hit, Miss and Eviction metrics to be emitted as delta increase/decrease

---

release-notes/opendistro-for-elasticsearch-performance-analyzer.release-notes-1.10.1.0.md

Update release notes for 1.10.1 release

Update release notes for 1.10.1 release

---

build.gradle

A community user found a bug in the links stated in package descriptions. check the post [here](https://discuss.opendistrocommunity.dev/t/unable-to-setup-apt-repo-for-opendistro-in-our-org/3124)
Fix download and doc link in the package description

Fix download and doc link in the package description

---

build.gradle

#204 (Note, this pr only partially fixes the issue)
When developing the batch metrics api, it was noticed that *Test.class files were not being detected for testing. This was addressed by adding one line of code to build.gradle (#159). However, it looks like adding that code has caused other tests to fail (these tests only fail on github, not on a laptop). So, this pr undoes that change. We will address the actual fix to the attached issue using a separate pr -- this undo is simply to clear up the build pipeline.

Remove addition of new tests

---

src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/config/PerformanceAnalyzerController.java

*Fixes #, if available:* https://github.com/opendistro-for-elasticsearch/performance-analyzer/issues/208
*Description of changes:* Enable RCA Framework by default.
[initRcaStateFromConf()](https://github.com/opendistro-for-elasticsearch/performance-analyzer/blame/080a62b4efc6eb30f23fa7bc3654b8032f133217/src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/config/PerformanceAnalyzerController.java#L175) initializes the RCA Conf file `rca_enabled.conf`, which is used by the RCA controller to enable/disable the framework.
As part of bootstrap, the `initRcaStateFromConf()` on not finding the `rca_enabled.conf` file, uses the default value for rcaEnabled. This code changes updates this value to 'true' from 'false'. 
By submitting this pull request, I confirm that my …

Enabling RCA framework by default

---

src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/ThreadPoolMetricsCollector.java

threadpool capacity is currently being read from ThreadPoolStats which requires core ES changes. What we can do instead is to update Threadpool metric collector to use reflection to read queue capacity. 

Update Threadpool metric collector to use reflection to read queue capacity

---

build.gradle
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/ConfigOverridesIT.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/PerformanceAnalyzerIntegTestBase.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/PerformanceAnalyzerRCAHealthCheckIT.java

#196 
Adds integration test for the override api

Add integration test for the /override API

---

src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/http_action/config/PerformanceAnalyzerResourceProvider.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/config/PerformanceAnalyzerClusterSettingHandlerTests.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/http_action/config/PerformanceAnalyzerResourceProviderTests.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/reader_writer_shared/EventLogFileHandlerTests.java

*Fixes #, if available:* Adding the Support to Proxy the call over to the _agent for Actions API
*Description of changes:* Add the proxy support as well as enable tests which were not enabled due to `Test` file name instead of a `Tests` filename.  
*Tests:*
=======================================
> Task :spotbugsMain
Warning at xsl:variable on line 348 column 57 of default.xsl:
SXWN9001: A variable with no following sibling instructions has no effect
Warning at xsl:variable on line 351 column 57 of default.xsl:
SXWN9001: A variable with no following sibling instructions has no effect
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See …

Adding the Support to Proxy the call over to the _agent for Actions API

---

src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/PerformanceAnalyzerPlugin.java
src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/MasterThrottlingMetricsCollector.java
src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/util/Utils.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/MasterThrottlingMetricsCollectorTests.java

Description of changes:
Code change is for Master Throttling of Pending task. It will publish two metric 1) Total throttled tasks at master node 2) Number of task on which data node is actively retrying. This feature is yet to be contributed to Opensource ES. I have added the check for availability of this feature in collector so building with or without this feature will pass. If this feature is not available then collector will simply return. 
Testing
1. /gradlew test Successful
2. Tested in test domain by replacing JAR.
Tmp file
```
^master_throttling_metrics
{"current_time":1602617137529}
{"Data_RetryingPendingTasksCount":0,"Master_ThrottledPendingTasksCount":0}$
```
Verified metric from table
```
sqlite> select * from Master_ThrottledPendingTasksCount;
0.0|0.0|0.0|0.0
```
By …

Add MasterThrottlingMetric Collector

---

src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/config/setting/handler/ConfigOverridesClusterSettingHandler.java
src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/http_action/config/PerformanceAnalyzerOverridesClusterConfigAction.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/MasterServiceMetricsTests.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/config/ConfigOverridesTestHelper.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/config/setting/handler/ConfigOverridesClusterSettingHandlerTests.java

*Fixes #, if available:*https://github.com/opendistro-for-elasticsearch/performance-analyzer-rca/issues/487
*Description of changes:*This change is to add support for enabling and disabling collectors through Rest API
```
[root@214d9f4eda93 performanceanalyzer]# curl -X POST "localhost:9200/_opendistro/_performanceanalyzer/override/cluster/config" -H 'Content-Type: application/json' -d'
> {
>   "enable": {
>    },
>   "disable": {
>       "collectors": ["MasterServiceMetrics"]
>    }
> }
> '
{"override triggered":true}[root@214d9f4eda93 performanceanalyzer]#
[root@214d9f4eda93 performanceanalyzer]# curl -X GET "localhost:9200/_opendistro/_performanceanalyzer/override/cluster/config"
{"overrides":"{\"enable\":{\"rcas\":[],\"deciders\":[],\"actions\":[],\"collectors\":[]},\"disable\":{\"rcas …
```

Enable disable collectors

---

src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/PerformanceAnalyzerPlugin.java
src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/ShardStateCollector.java
src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/config/PerformanceAnalyzerController.java
src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/util/Utils.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/ShardStateCollectorTest.java

*Fixes #, if available: https://github.com/opendistro-for-elasticsearch/performance-analyzer/issues/213*
This change will start publishing shard state - Initializing, Unassigned and Relocating for each shard. We have not published Active shards to save space.
Testing
1. ./gradlew test
```
SUCCESS: Executed 455 tests in 41m 55s (1 skipped)
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings
BUILD SUCCESSFUL in 42m 22s
11 actionable tasks: 2 executed, 9 up-to-date
```
2. Tested using docker.
Tmp File - 
```
^shard_state_metrics
{"current_time":1602500493586} …
```

Publish shard state metrics

---

src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/PerformanceAnalyzerPlugin.java
src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/MasterThrottlingMetricsCollector.java
src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/util/Utils.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/MasterThrottlingMetricsCollectorTests.java

Description of changes:
Code change is for Master Throttling of Pending task. It will publish two metric 1) Total throttled tasks at master node 2) Number of task on which data node is actively retrying. This feature is yet to be contributed to Opensource ES. I have added the check for availability of this feature in collector so building with or without this feature will pass. If this feature is not available then collector will simply return.
PR of this was mistakenly merged before approval. Raised same PR again.
Old PR: #217
Testing
/gradlew test Successful
Tested in test domain by replacing JAR.
Tmp file
^master_throttling_metrics {"current_time":1602617137529} {"Data_RetryingPendingTasksCount":0,"Master_ThrottledPendingTasksCount":0}$
Verified metric from table
sqlite> select * from …

Add Master Throttling Collector Metrics

---

src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/FaultDetectionMetricsCollectorTests.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/ShardStateCollectorTests.java

These tests did not run previously since they were not named according to the convention "*Tests". Changing test name in this PR and changing logic to make it pass.

Fixing test name and AES build

---

src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/NodeStatsAllShardsMetricsCollector.java

*Fixes #, if available:* #230 
*Description of changes:* We were reporting the diff metric for the Query Cache, Field Data Cache and Request Cache. Updated it to report the actual Value and not just the difference in metric.  

Updating the Actual Cache Values and not the Delta

---

.github/workflows/gradle.yml
README.md
build.gradle

*Fixes #, if available:* #236 
1. add jacoco to set up code coverage.
2. show code coverage report for every pull request in future.
3. integrate with "codecov" to show latest code coverage badge in REAMDE file.

set up jacoco for code coverage

---

src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/http_action/config/PerformanceAnalyzerResourceProvider.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/http_action/config/PerformanceAnalyzerResourceProviderTests.java

*Fixes #, if available:* The web-server port has been [updated](https://github.com/opendistro-for-elasticsearch/performance-analyzer/blob/master/pa_config/performance-analyzer.properties#L18) to 9600 but the default port has not been changed (9650). Changed the default port to 9600 to avoid any discrepancies. 
*Testing:* Tested on docker by running PA and checking if the service is up on original port 9600. 

Changing Default Port for the Webserver 

---

build.gradle

*Fixes #, if available:* https://github.com/opendistro-for-elasticsearch/performance-analyzer/issues/249
*Description of changes:* Upgrade dom4j to 2.1.3+
Updating the com.github.spotbugs to latest 4.6.0 version, which will bring in 2.1.3 version of dom4j
```
khushbr@3c22fb8556dd performance-analyzer % ./gradlew :dependencyInsight --configuration spotbugs --dependency org.dom4j
=======================================
Elasticsearch Build Hamster says Hello!
Gradle Version        : 6.6.1
OS Info               : Mac OS X 10.15.7 (x86_64)
JDK Version           : 15 (JDK)
JAVA_HOME             : /Library/Java/JavaVirtualMachines/amazon-corretto-15.jdk/Contents/Home
Random Testing Seed   : D4919ADDC9EDBED4
In FIPS 140 mode      : false
=======================================
> Task …
```

Upgrade dom4j to 2.1.3+

---

build.gradle
checkstyle/checkstyle.xml

*Fixes #, if available:* https://github.com/opendistro-for-elasticsearch/performance-analyzer/issues/247
*Description of changes:* Upgrading commons-beanutils to 1.9.4. This `commons-beanutils:commons-beanutils:1.9.3` is coming from `com.puppycrawl.tools:checkstyle:8.20`.  Added 'checkstyle' plugin with 'com.puppycrawl.tools:checkstyle:8.37' dependency. Also, added checkstyle.xml
```
checkstyle - The Checkstyle libraries to be used for this project.
\--- com.puppycrawl.tools:checkstyle:8.20
+--- info.picocli:picocli:3.9.6
+--- antlr:antlr:2.7.7
+--- org.antlr:antlr4-runtime:4.7.2
+--- commons-beanutils:commons-beanutils:1.9.3
|    \--- commons-collections:commons-collections:3.2.2
+--- com.google.guava:guava:27.1-jre
|    +--- com.google.guava:failureaccess:1.0.1
|    +--- …
```

Upgrading commons-beanutils to 1.9.4

---

src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/writer/EventLogQueueProcessor.java

1. Currently when the metrics PA collects arrive late, then it will be logged as info message. Instead we create a new metric STALE_MERIC and aggregate the count.

aggregate stale metrics to write_metrics

---

build.gradle

Changes for the Performance Analyzer IT to run with newer versions of ES

---

THIRD-PARTY
build.gradle

*Fixes #:*
Upgrade jackson-databind to 2.12.0 according to CVE-2020-25649
Update THIRD-PARTY
*Tests:*
*If new tests are added, how long do the new ones take to complete*

Upgrade jackson-databind to 2.12.0

---

THIRD-PARTY
build.gradle

This reverts commit 33e233b1d0d6345703a9dfab0c37cb176f206e5f.
jackson-databind is set back to 2.10.4

Revert "Upgrade jackson-databind to 2.12.0 (#259)"

---

src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/integ_test/CpuMetricsIT.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/integ_test/MetricCollectorIntegTestBase.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/integ_test/PageFaultMetricsIT.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/integ_test/json/JsonResponseData.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/integ_test/json/JsonResponseField.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/integ_test/json/JsonResponseNode.java

Add integ tests for OS metrics(cpu, page fault)

Add integ tests for OS metrics(cpu, page fault)

---

build.gradle
pa_config/supervisord.conf
packaging/deb/postinst
packaging/performance-analyzer-agent-cli
packaging/rpm/postinst
src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/PerformanceAnalyzerPlugin.java

*Fixes #, if available:*  Update the Performance Analyzer Package with new naming Convention for ODFE
*Description of changes:* Updated the naming Convention of the binaries for Linux and Mac with the latest naming convention for ODFE
Artifacts after the change: 
```            
opendistro-performance-analyzer-1.12.0.0-SNAPSHOT.zip
opendistro-performance-analyzer-1.12.0.0.deb	
opendistro-performance-analyzer-1.12.0.0.rpm	
[root@af817ef5ccf6 elasticsearch]# curl "localhost:9600/_opendistro/_performanceanalyzer/metrics?metrics=Latency,CPU_Utilization&agg=avg,max&dim=ShardID&nodes=all" | python -m json.tool
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- …
```

Naming Changes to match the ODFE Naming Convention

---

build.gradle

Use jackson version 2.10.5 to fix CVE-2020-25649 

Fix jackson cve

---

src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/integ_test/HeapMetricsIT.java

https://github.com/opendistro-for-elasticsearch/opendistro-build/issues/339
Currently we expect the max heap to be within 512MB, however, for our integration tests hooked up with the infra team, the max heap size is 1GB. This causes the heap metrics integ test to fail.
This change increases the max limit to check against to 2GB from 512MB.
license and I have the right …

Increase the max heap limit to check against in the integ tests

---

src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/PerformanceAnalyzerPlugin.java
src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/ShardIndexingPressureMetricsCollector.java
src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/util/Utils.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/ShardIndexingPressureMetricsCollectorTests.java

*Issue #, if available:* [perf-analyzer-rca/561](https://github.com/opendistro-for-elasticsearch/performance-analyzer-rca/issues/561)
Code changes to add a new collector.
Below are the metrics that will be collected.
1. rejectionCount - Keeps track of the rejection count.
2. currentBytes - Keeps track of the inflight request size.
3. currentLimits - Keeps track of the shard limits(logic internal to AES).
4. averageWindowThroughput - Keeps track of the average throughput of last N requests.
5. lastSuccessfulTimestamp - Keeps track of the timestamp of last successful request.
These metrics are published with following dimensions -
1. indexingStage - Coordinating, Primary or replica.
2. indexName - Name of the index.
3. shardId - Id of the shard.

Changes to collect shard indexing pressure metrics and push to shared location

---

src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/ShardIndexingPressureMetricsCollector.java

*Issue #, if available:* https://github.com/opendistro-for-elasticsearch/performance-analyzer/issues/283
Added a check to just process first 50 objects of hot store. This is a safe guarding mechanism to avoid processing of n items in the hot store and eventually leading to degraded performance of rca agent.
*Testing*
https://ideone.com/l9HsoH
license and I have the right under that license to …

Adding a additional check to just process first 50 objects of hot store

---

src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/ShardIndexingPressureMetricsCollector.java

Publishing Error and Writer metrics - https://github.com/opendistro-for-elasticsearch/performance-analyzer-rca/issues/567
*Related PR :* https://github.com/opendistro-for-elasticsearch/performance-analyzer-rca/pull/569
Added the logic to publish the metrics for error and writer. Error metrics is published when there is any error that happens during parsing the hot store objects.
*Testing*
The collector is enabled by default and we can see the metrics once we enable the ES feature.
Once the collector is disabled we can see that there are no metrics even though the ES feature is enabled or disabled.
(a) The contribution was created in whole or in …

Added metrics publishing logic

---

src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/PerformanceAnalyzerPlugin.java
src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/AdmissionControlMetricsCollector.java
src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/util/Utils.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/AdmissionControlMetricsCollectorTests.java

*Issue #, if available:* 
https://github.com/opendistro-for-elasticsearch/performance-analyzer-rca/issues/570
Publish AdmissionControl framework (external) metrics. These metrics are generated at node level.
- rejectionCount - Keeps track of the rejection count.
- currentValue - Keeps track of the controller's resource (Global JVM Memory Pressure / Request Size) current value.
- thresholdValue - Keeps track of the controller's resource (Global JVM Memory Pressure / Request Size) threshold value. 
(b) The contribution is …

Track admission control metrics

---

src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/AdmissionControlMetricsCollectorTests.java

*Issue #, if available:* https://github.com/opendistro-for-elasticsearch/performance-analyzer/issues/299
AdmissionControl: Clear metricQueue before running test
work with modifications, whether created in whole or in part
by me, under the same open source license (unless I am
permitted to submit under a different license), as indicated …

AdmissionControl: Clear metricQueue before running test

---

src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/MasterServiceMetrics.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/MasterServiceMetricsTests.java

**Master Pending Queue size per task type**
Earlier we were publishing Total number of pending task. For RCA analysis Pending Queue size per task type will give better understanding. Changed total Queue Size to Queue size per task type
_Tests:_
Added some manual entry. Below are the output of manual entry
_1. Output of tmp file_
```
^pending_tasks/current/metadata
{"current_time":1610945977204}
{"Master_PendingQueueSize":5,"Master_PendingTaskType":"create"}
{"Master_PendingQueueSize":3,"Master_PendingTaskType":"delete"}
{"Master_PendingQueueSize":10,"Master_PendingTaskType":"shard-started"}$
```
_2. Table of Master_PendingQueueSize_
```
sqlite> select * from Master_PendingQueueSize;
create-index|5.0|5.0|5.0|5.0
delete-index|3.0|3.0|3.0|3.0
shard-started|10.0|10.0|10.0|10.0
```
By …

Changed master total PendingQueueSize to PendingQueueSize per task type

---

build.gradle
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/ElectionTermCollectorTests.java

Fix the failing election term test. Enable the collector (by mocking)
Reduce the test coverage limit to 0.7 to avoid build failure.
Tracking the task to increase coverage in this issue (https://github.com/opendistro-for-elasticsearch/performance-analyzer/issues/306)
work with modifications, whether created in …

Fix failing election term tests and CI

---

src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/writer/EventLogQueueProcessor.java
src/test/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/reader_writer_shared/EventLogFileHandlerTests.java

https://github.com/opendistro-for-elasticsearch/performance-analyzer/issues/313
We write to tmp files first before renaming to actual epoch file.
Append/ Create to the tmp file only if we have metrics to publish.
work with modifications, whether created in whole or in part
by me, under the same open source …

Create writer file if metrics are available
